import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from extract_rare import *

df_train_collated = pd.read_csv('../input/all_without_date/collated/all_columns/df_train_collated.csv')
df_test_collated = pd.read_csv('../input/all_without_date/collated/all_columns/df_test_collated.csv')

directory = 'demo/'
if not os.path.exists(directory):
    os.makedirs(directory)

# density plot of demand in training data
sns.distplot(df_train_collated['demand'], hist=False, kde=True, kde_kws={'linewidth': 3},label='demand')\
    .set(title='distribution of demand in training data',
        label='demand',
        ylabel='density')
plt.savefig(os.path.join(directory, 'density_training'))
plt.close()


# density plot of demand in testing data
sns.distplot(df_test_collated['demand'], hist=False, kde=True, kde_kws={'linewidth': 3},label='demand')\
    .set(title='distribution of demand in testing data',
        label='demand',
        ylabel='density')
plt.savefig(os.path.join(directory, 'density_testing'))
plt.close()

# plot the automatic relevance generated by
combined = pd.concat([df_train_collated, df_test_collated])
y = combined['demand']
yrel = get_relevance(y=y, df=None, target_variable=None, method='extremes', extr_type='both', control_pts=None)
plot_relevance(y, yrel, target_variable='demand', output_folder=directory, fig_name='relevance')

